### ISSUE TITLE
setCategories() gives nested userOptions

### ISSUE THREAD

**Issue by Resin01** [blacklabel/grouped_categories#103]
If I have setup my categories like this
`[{name: 'All', nps: 3.2},{name:'Company',nps:4}]`
and then later extract the data from it to change them (say remove a column)
Now when I add them back in using setCategories() I end up with having eg. categories[0].userOptions.userOptions, with my data (instead of categories[0].userOptions)

Jsfiddle showing the issue in the console
http://jsfiddle.net/TFhd7/1286/

**Comment by pawelfus** [comment]
Hi @Resin01 

Thank you for reporting the issue. Workaround: http://jsfiddle.net/TFhd7/1287/

```
  categories = categories.map(category => category.userOptions);
```

Of course, there shouldn't be **any** `userOptions`.

**Comment by Resin01** [comment]
Thanks. I already have made a fix myself :)
