### ISSUE TITLE
Possible to Extend to Include Optional HEADER Labels for each level?

### ISSUE THREAD

**Issue by mzhukovs** [blacklabel/grouped_categories#104]
I'm using your plugin (which is fantastic btw, thanks very much) in a bit of a unique way, the categories aren't really grouped, instead, each has exactly one child, so that way I can create what looks like a table in the heatmap chart (see attached).

One issue I ran into is that it's tough to add labels to each layer (in this case, each "column"). As a work around, I'm using a re-positioned y-axis title label with slashes to separate the column names...but it isn't a great approach. I was wondering if you would be so kind to provide an update (or some guidance) on how the attached could be achieved, where your plug-in would accept an optional array of headers per layer:

![groupedcategorieswithcolumnheadings](https://cloud.githubusercontent.com/assets/13161978/24188894/fc607cd4-0f1d-11e7-9e0e-c40f45508792.png)

Would be much appreciated, thank you!

**Comment by pawelfus** [comment]
Hi @mzhukovs 

Thanks! It's great to hear that you like our plugin :)

Regarding your request, I think you can achieve this in two ways:
- create one more category on top of the chart with titles. That will easily resolve 1), 2a) and 3) points. 2) point will behave like any other category
- use `chart.renderer()` to render manually labels. That will resolve 1), 2) and 3) point. However 2a) will not resize category (you need to remember, it's grouped-categories plugin, not axis-table).

However, I think what you really need is a GridAxis module from Highcharts Gantt. You can read more on [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/804783-gantt-chart). From alpha description:

> GridAxis: Makes axes look like table rows or cells
