### ISSUE TITLE
Be able to disable grid part

### ISSUE THREAD

**Issue by yohannbalawender** [blacklabel/grouped_categories#105]
Hi, as pointed out by the following chart:

https://jsfiddle.net/q2yphg8z/
![chart 3](https://cloud.githubusercontent.com/assets/6325305/24356398/107ac76c-12fa-11e7-9f59-2df3cfe40b75.png)

I have got very long rotated labels which are overlapping grid part.

In this case we do not have the place to draw grid part (note that this is a simple example and my charts are more complex - depending on the case, I can have more than 100 labels in two groups).

So IMHO we should be able to either disable grid through an option or disable automatically if labels are overlapping grid.

Thank you.

**Comment by pawelfus** [comment]
Hi @yohannbalawender 

You can disable grid by setting `xAxis.tickWidth`, see: https://jsfiddle.net/q2yphg8z/1/

**Comment by yohannbalawender** [comment]
Indeed, thank you @pawelfus !
