### ISSUE TITLE
grouped-category point label

### ISSUE THREAD

**Issue by asimnzr** [blacklabel/grouped_categories#107]
Hi,

I am using this plugin for one of my scenario and it is working really great but I need to add label under each point in a group. I tried explaining it using below snapshot:

![chart](https://cloud.githubusercontent.com/assets/10372429/24447239/b14f6900-1489-11e7-9189-d0cc7f825360.png)

In the snapshot I need two labels for each point (e.g. "Co Sales" and "S Sales") instead of Category wise label ("Sales"). Is there any solution for this?

Thanks in anticipation!

**Comment by pawelfus** [comment]
You can get text in vertical layout this way: https://jsfiddle.net/kg7chrub/ however it's tricky, as both texts should be the same length. Also you need to use `tooltip.formatter` to change the format of the tooltip.

**Comment by asimnzr** [comment]
Thanks!
