### ISSUE TITLE
Not working grouped categories

### ISSUE THREAD

**Issue by manigor** [blacklabel/grouped_categories#108]
Created chart based on highcharts
http://jsfiddle.net/manigor/Lksew8j9/2/
Strange, but i cant make it work, see no reason, why its not working, first time grouped is broken so strong.

**Comment by pawelfus** [comment]
You didn't load grouped categories plugin. In the JS console you can see script is blocked: 

> Refused to execute script from 'https://raw.githubusercontent.com/blacklabel/grouped_categories/master/grouped-categories.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Github long time ago disabled direct link to script from a raw file. 

Works fine with package url from gh-pages: http://jsfiddle.net/Lksew8j9/3/
