### ISSUE TITLE
Label styling like rotation and etc., for different levels

### ISSUE THREAD

**Issue by scottszb1987** [blacklabel/grouped_categories#109]
Hi there,

At the moment xAxis.labels controlls the styles of labels for the the entire xAxis, It is expected that each level of categories can be individually styled, do you guys have a plan to add such functionalities in future?

Cheers

**Comment by pawelfus** [comment]
It's already supported: https://github.com/blacklabel/grouped_categories

> For each level you can define subset of styling options. 0-level categories are based on the default Highcharts options.

```
xAxis: {  	
	labels: {
	    groupedOptions: [{
	  	    style: {
	  	  	    color: 'red' // set red font for labels in 1st-Level  
	  	    }
	    }, {
	  	    rotation: -45, // rotate labels for a 2nd-level
	  	    align: 'right'
	    }],
	    rotation: 0 // 0-level options aren't changed, use them as always
    },
    ...
```

**Comment by scottszb1987** [comment]
Thanks, that's really awesome.

**Comment by sagarv-vitara** [comment]
Hey @pawelfus I think there seems to be a problem. The rotation is not working http://jsfiddle.net/4avqu8k6/

**Comment by pawelfus** [comment]
Hi @sagarv-vitara 

Use `xAxis.labels.groupedOptions[index].rotation`, not `xAxis.labels.groupedOptions[index].styles.rotation` :) Updated demo: http://jsfiddle.net/BlackLabel/f5jztq28/2/

**Comment by sagarv-vitara** [comment]
Hi @pawelfus,

sorry that was a mistake on my end. But the issue I'm referring to is rotating the H1, H2 labels.

In the code

```
groupedOptions: [{
  rotation: -60, // 1st level
}, {
  rotation: -45, // rotate labels for a 2nd-level
  align: 'right'
}]
```

The second object seems ignored. The second level labels still have 0 rotation

**Comment by KacperMadej** [comment]
Standard Highcharts labels are still controlled in the default Highcharts API, so 0 level is the one controlling rotation of H1, H2 labels. Demo: http://jsfiddle.net/BlackLabel/f5jztq28/3/

**Comment by sagarv-vitara** [comment]
Ah now it makes sense. I was thinking the main category as L0 and the one close to chart as L1.

Now it's clear. Thanks @KacperMadej @pawelfus
