### ISSUE TITLE
Showing label for each stack in a series

### ISSUE THREAD

**Issue by alexanderdevm** [blacklabel/grouped_categories#114]
Good Afternoon,

I am trying to show a label for each stack, like this: https://i.stack.imgur.com/grKmL.png

Although when i try to implement it, it groups the stacks together under one label : http://jsfiddle.net/02ey1hbr/7/

`
 Highcharts.chart('container', {
    chart: {
        type: 'bar'
    },
    title: {
        text: 'Stacked bar chart'
    },
    xAxis: {
      labels: {
                    rotation: -0,
                    style: {
                        fontSize: '10px',
                        align: 'Right',
                    }
                },
        categories: [{
                name: "Case A",
                categories: ["Male", "Female"]
            }, {
                name: "Case B",
                categories: ["Male", "Female"]
            }]
    },
    yAxis: {
        min: 0,
        title: {
            text: 'x-axis'
        }
    },
    legend: {
        reversed: true
    },
  plotOptions: {
    bar: {
      stacking: 'normal'
    }
  },
    series: [{
        name: 'x',
        data: [5,3,4,5],
				stack: 'StackA'
    }, {
        name: 'y',
        data: [3,5,4,5],
        stack: 'StackA'
        },{
        name: 'x',
        data: [5,3,4,5],
				stack: 'StackB'
    }, {
        name: 'y',
        data: [3,5,4,5],
        stack: 'StackB'
        }
    ]
});
`

**Comment by pawelfus** [comment]
There's not category per stack, only per point. That way you can use `null` points to generate an offset for empty categories. Take a look: http://jsfiddle.net/02ey1hbr/9/
