### ISSUE TITLE
Need help: Adding dynamic values to parent names.

### ISSUE THREAD

**Issue by poojaguptez** [blacklabel/grouped_categories#115]
Assume that I am declaring chart with following code. Now, I want to modify "name" for each object under categories array. How can I do that.? Currently I am trying to do it with this code "chart.xAxis[0].categories[o].parent.name", but it's not reflecting on the UI.

var chart = new Highcharts.Chart({
- - - //other chart parameters
xAxis: {
            categories: [{
                name: "1/1/2014",
                categories: ["Vendor 1", "Vendor 2", "Vendor 3"]
            }, {
                name: "1/2/2014",
                categories: ["Vendor 1", "Vendor 2", "Vendor 3"]
            }, {
                name: "1/3/2014",
                categories: ["Vendor 1", "Vendor 2", "Vendor 3"]
            }]
        }
 });

Thanks in advance.

**Comment by pawelfus** [comment]
Use [`xAxis.setCategories()`](http://api.highcharts.com/highcharts/Axis.setCategories) method.
