### ISSUE TITLE
Change in Highcharts (version 5.0.13 (2017-07-27))

### ISSUE THREAD

**Issue by DirkDeWachter** [blacklabel/grouped_categories#116]
From the changelog:
•Added pos, axis position, to axis label formats. Closes #6859.

pos is not (yet) added in the call to labelFormatter (src-line 383)

**Comment by KacperMadej** [comment]
Hi,

In the code the change is present.
Working demo: http://jsfiddle.net/un65bckb/

Please post a demo of the problem if it is possible to recreate it and the issue will be reopened.

**Comment by DirkDeWachter** [comment]
Hi,

I was simply reading the code:
```
	tickProto.addLabel = function () { 
373 		var category; 
374 		 
375 		protoTickAddLabel.call(this); 
376 		 
377 		if (!this.axis.categories || !(category = this.axis.categories[this.pos])) { 
378 			return false; 
379 		} 
380 		 
381 		// set label text - but applied after formatter #46 
382 		if (this.label) { 
383 			this.label.attr('text', this.axis.labelFormatter.call({ 
384 				axis: this.axis, 
385 				chart: this.axis.chart, 
386 				isFirst: this.isFirst, 
387 				isLast: this.isLast, 
388 				value: category.name 
389 			})); 
390 		} 

```
In the call to this.axis.labelFormatter (line 383) pos is not handed over. The "pos"-argument should be added to this call:
` 				pos: this.pos, `
