### ISSUE TITLE
No borderlines on HeatMap

### ISSUE THREAD

**Issue by Jama1ka** [blacklabel/grouped_categories#118]
No axis labels borderlines on HeatMap
http://jsfiddle.net/7xae1s17/1/

**Comment by pawelfus** [comment]
Hi @Jama1ka 

Do you mean that plotBorder is not visible on the axes lines? Axis' line has a higher zIndex than plotBorder, so it's rendered higher:

![screen shot 2017-09-14 at 15 33 17](https://user-images.githubusercontent.com/1453926/30432579-5f2ee46c-9962-11e7-9055-4da710d0fa4a.png)

You can disable axes lines, [demo](http://jsfiddle.net/BlackLabel/7xae1s17/2/).

**Comment by Jama1ka** [comment]
Hi @pawelfus, ty for your answer

**Comment by pawelfus** [comment]
My apologies, I just realized you mean border around grouped categories, not the plotting area. The more detailed issue description, the better answer ;)

To enable borders, set `tickWidth`, take a look: http://jsfiddle.net/BlackLabel/7xae1s17/3/
