### ISSUE TITLE
Multiple series

### ISSUE THREAD

**Issue by mikaelorn** [blacklabel/grouped_categories#120]
In all the examples the datapoints are placed in the correct category according to their index in the array. Is there a feature to handle multiple series and go by series name or id? i havent been able to find any way of doing this. My data is split into multiple series and i cant smash it into one series.

**Comment by pawelfus** [comment]
Hi @mikaelorn 

Could you show your data sample? In general, multiple series works the same way as just one series, for example: https://jsfiddle.net/BlackLabel/TFhd7/1643/

You don't have to base on index in the data array, you can provide `x` value for points, for example: https://jsfiddle.net/BlackLabel/TFhd7/1644/

**Comment by mikaelorn** [comment]
Thank you the second example will work!

**Comment by pawelfus** [comment]
Ok, thanks for the info!
