### ISSUE TITLE
Styles for different levels defined by groupedOptions don't seem to work

### ISSUE THREAD

**Issue by daniel-araujo** [blacklabel/grouped_categories#121]
**Example code**
http://jsfiddle.net/xzus78o0/

**Expected behavior**
The first level should be colored red and the second level should be colored green.

**Actual behavior**
Only the first level is colored red. The options for the second level seem to be ignored.

**Comment by pawelfus** [comment]
Hi @daniel-araujo 

The 0-level of categories is controlled by default Highcharts options, see third snippet from docs: https://github.com/blacklabel/grouped_categories#usage-and-demos

Demo: http://jsfiddle.net/BlackLabel/xzus78o0/3/

**Comment by daniel-araujo** [comment]
Thanks. Missed that detail, my bad.
