### ISSUE TITLE
How can I remove the border of xAxis label?

### ISSUE THREAD

**Issue by rudyhuynh** [blacklabel/grouped_categories#123]
<img width="667" alt="2018-07-02_1822" src="https://user-images.githubusercontent.com/17097854/42161392-06f92ee4-7e25-11e8-8c67-e404f646337f.png">

**Comment by sebastianbochan** [comment]
Hi @rudyhuynh,
You can remove it by setting `tickWidth` as 0.

**Demo:**
- https://jsfiddle.net/BlackLabel/xrf6we5p/

Is it your requested layout?
