### ISSUE TITLE
Grouped label positioning issue for scrollable chart

### ISSUE THREAD

**Issue by techMGraph** [blacklabel/grouped_categories#124]
In case of a scrollable bar-chart with grouped categories, for really long data with different number of child items under parent categories, some parent label positions behave unexpectedly. Here's a [fiddle demonstrating the issue](http://jsfiddle.net/da980xja/9/).
![screen shot 2018-07-12 at 12 14 05 pm](https://user-images.githubusercontent.com/41140265/42617933-1d9cda02-85d1-11e8-9619-e954b697e816.png)
In above screenshot, "Wed 04/18/2018" is taking up the space of "Shift-1" of "Thu 04/19/2018". The divider is also misplaced as a result.

The positions are fine when one begins scrolling towards the end. Once we start scrolling backwards, some of the labels that were positioned fine earlier get mispositioned when scrolling back. I'm able to reproduce this issue every time on the given fiddle.

This might be linked to https://github.com/blacklabel/grouped_categories/issues/18

**Comment by pawelfus** [comment]
Hi @techMGraph 

This looks exactly like #55 issue.

**Comment by techMGraph** [comment]
I'd like to add that this happens in my case when the child categories array for parent categories do not necessarily have the same length. For ex from above screenshot, `Wed 04/18/2018` might have children `['Shift-1' , 'Shift-2']` while `Thu 04/19/2018` might have `['Shift-1']`. So this might be a calculation issue as well
