### ISSUE TITLE
Not work on csvURL

### ISSUE THREAD

**Issue by vdhung** [blacklabel/grouped_categories#127]
I have csvURL get data:
Example:
Title, LineId, Percents, Value
Line 1, 1-1, 20.2, 30
Line 2, 2-1, 30.2, 80
Line 2, 2-2, 26.2, 70

-----------------
I get data from CSV (from element on webpage), this run OK. Because  I thing , xAxis categories seted.
But, I using csvURL : get categories and data, not working.
Please help me, tks.
-----------------------------------
`data: {
            csvURL: url,
            enablePolling: true,
            dataRefreshRate: 5,
            seriesMapping: [{ x: 0, processId: 1, y: 2, label: 3 }],
            complete: function (e) {
                var ds = e.series[0].data, arr = [], arrComplete = [];
                for (var i = 0 ; i < ds.length; i++) {
                    var ind = arr.indexOf(ds[i].name)
                    if (ind < 0) {
                        arr.push(ds[i].name);
                        arrComplete.push({ name: ds[i].name, categories: [ds[i].processId] });
                    }
                    else
                        arrComplete[ind].categories.push(ds[i].processId)
                }
                e.xAxis.categories = arrComplete;
                _categories = arrComplete;
            },
            parsed: function (e) {
                console.log('parsed')
            }
        },
        title: { text: null },
        xAxis: {
            type: "category",
            labels: {
                useHTML: true,
                rotation: -90,
                style: {
                    height: 'auto',
                    padding: '0px 0px 0px 10px',
                    textAlign: 'right'
                }
            },
            gridLineWidth: 1,
            gridLineColor: '#e6e6e6'
        },`

**Comment by sebastianbochan** [comment]
Hi @vdhung,
Thank you for contacting us. This is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use forum / stackoverflow or email.
