### ISSUE TITLE
Categories borders custom style 

### ISSUE THREAD

**Issue by frntnd93** [blacklabel/grouped_categories#138]
Hi, thank you very much for this module.
Help me, please, I need to adjust the style of the frame, as in the picture.
is it possible and how can i do it? I tried for a few days and nothing works

![1](https://user-images.githubusercontent.com/41643887/59441116-c05d6080-8e00-11e9-80e5-8f5275437337.jpg)

**Comment by pawelfus** [comment]
Color for the grid is taken from `xAxis.tickColor`, demo for you: https://jsfiddle.net/BlackLabel/xrf6we5p/10/
