### ISSUE TITLE
Auto Rotation is not working

### ISSUE THREAD

**Issue by prabhujeevan** [blacklabel/grouped_categories#142]
https://jsfiddle.net/5d2x89mL/1/
please refer the jsfiddle. Here i have included the grouped categories.js.. So the auto rotation is not working in the new version 8.0.. but same thing working fine in version 6.1.2. anyway if i remove the grouped categories.js means, the auto rotation working fine. please do the needful me.

**Comment by PaulDalek** [comment]
Hi @prabhujeevan 

Thanks for reporting this issue.

**Workaround:**
Creating the textPxLength property `tick.label.textPxLength = tick.label.getBBox().width;` for the label near the end of the `addLabel` function (override from the grouped categories plugin) seems to resolve the problem.

**Live demo:**
https://jsfiddle.net/BlackLabel/j8r3hbux/

**Comment by pawelfus** [comment]
Works fine since Highcharts v8.1.2: https://jsfiddle.net/BlackLabel/rqmk239d/
