### ISSUE TITLE
After adding new series the 0 level category name is added to 1 level category

### ISSUE THREAD

**Issue by mateuszkornecki** [blacklabel/grouped_categories#143]
**Actual behavior:**
After adding a new series, the name of the 0 level category is added to the one above.

**Steps to reproduce:**
Run the demo, then click on the "addSeries button" and look for changes at the name of 1 level categories

**Live demo:** http://jsfiddle.net/BlackLabel/vgjnumdb/

**Highcharts version:**
8.0.0

**Comment by onferflay** [comment]
Same behavior when you click on legend item ! in your example click on Series 2 and you will se the same thing! i used               
```
events: {
                  legendItemClick: function() {
                    return false;
                  }
              }
```
to avoid it but i prefer  to wrok properly! 

Thank you!

**Comment by mateuszkornecki** [comment]
Already fixed in https://github.com/blacklabel/grouped_categories/issues/146.
