### ISSUE TITLE
Javascript errors on scroll using highstock v8.0.0

### ISSUE THREAD

**Issue by ktakahashimtb** [blacklabel/grouped_categories#145]
Hi,
I have run into this issue after upgrading to Highcharts/Highstock 8.0.0.
In the example below, please zoom in and scroll either direction.

https://jsfiddle.net/ktakahashimtb/jnwxcesg/

Scrollbar looks stuck and there are numerous Javascript errors.

Any chance, this will be addressed in near future?
Thank you!

Kei

**Comment by Sivaramakrishnan1998** [comment]
I am also getting same issue. 
getting error in console(developer tool) as below:

grouped-categories.js:456 Uncaught TypeError: Cannot read property 'getBBox' of undefined
    at c.Tick.tickProto.addGroupedLabels (grouped-categories.js:456)

**Comment by pawelfus** [comment]
Thanks for reporting!

**Comment by arsinawaz** [comment]
I am also facing the same issue. Any update on this?
