### ISSUE TITLE
labels wrong when update charts highcharts v8.0.0 

### ISSUE THREAD

**Issue by wjhcc2018** [blacklabel/grouped_categories#146]
right picture:
![1](https://user-images.githubusercontent.com/6789138/74294609-65a64b00-4d79-11ea-87fc-72c88bb90b92.png)
wrong picture:
![2](https://user-images.githubusercontent.com/6789138/74294630-78208480-4d79-11ea-9914-95093945b3b9.png)
code:https://jshare.com.cn/temp/SeGrWa

**Comment by KacperMadej** [comment]
Hi @wjhcc2018 

Thank you for reporting the problem.

Updated labels are not updates correctly for the axis after the axis update.
Simple demo: https://jsfiddle.net/BlackLabel/TFhd7/5301/

**Comment by wjhcc2018** [comment]
@KacperMadej Thanks for your reply,can you give me some solutions?thanks

**Comment by pawelfus** [comment]
@mateuszkornecki - could you take a look? Thanks!

**Comment by mateuszkornecki** [comment]
_Internal note:_ Bisected to commit: https://github.com/highcharts/highcharts/commit/3479b699e2108f4f18da19bec4a3bf8cbb4dc8b1

**Comment by mateuszkornecki** [comment]
The problem is caused by data sorting which is not supported by the plugin yet. For a workaround, you could add the following code to your project: 
```
(function(H) {
    H.wrap(H.Tick.prototype, 'replaceMovedLabel', function(p) { });
}(Highcharts))
```
Live demo: https://jsfiddle.net/BlackLabel/qrab3knm/

**Comment by wjhcc2018** [comment]
I'm sorry that the problem has not been solved， **live demo :https://jshare.com.cn/temp/SeGrWa**
