### ISSUE TITLE
Grouping tick height is getting more and chart plot area height is becoming zero

### ISSUE THREAD

**Issue by santoshkotta** [blacklabel/grouped_categories#154]
Hi,
I am using Grouped Categories in my angular 7 application, I am observing some wrong behavior. On application loading I am getting proper display and format of the chart but whenever I am navigating from current page to another pages and came back to first page then display/ format is breaking. Could anyone help me to resolve this issue?

![image](https://user-images.githubusercontent.com/8666431/78458715-102f5000-76d1-11ea-9edf-115a600b4437.png)

![image](https://user-images.githubusercontent.com/8666431/78458727-2d641e80-76d1-11ea-8671-8c4dddefa0d4.png)

Thanks in advance.

**Comment by pawelfus** [comment]
Thanks for reporting @santoshkotta 

Could you provide live demo of the issue? We will check this.

Just a lucky guess: you load grouped-categories module multiple times. Please make sure it's loaded just once, after loading Highcharts lib.

**Comment by santoshkotta** [comment]
Hi pawelfus,

Your guess is correct, it's breaking because of multiple times module loading. Thanks for the quick response.
