### ISSUE TITLE
#146 is still occuring in v1.1.5

### ISSUE THREAD

**Issue by jwhitmarsh** [blacklabel/grouped_categories#157]
Here's an example with a `chart.redraw()` after 1s delay. You can see that there are now commas after each of the category names. 

![out](https://user-images.githubusercontent.com/8026009/83515643-9d263800-a4cd-11ea-8658-08084a4a6c04.gif)

**Comment by pawelfus** [comment]
Thanks for reporting! @mateuszkornecki - please, take a look. Demo: https://jsfiddle.net/BlackLabel/8jmp1rks/1/ - still does not work with v8.0.0+, works fine with v7.x.

**Comment by wjhcc2018** [comment]
@pawelfus I tested it on Highcharts V8.1.0 and the code did not solve the problem, which still exists

**Comment by mateuszkornecki** [comment]
@wjhcc2018 Thanks for reporting, it is already fixed on the master but it seems that the plugin was not published yet. Untill it is not published you can use the following workaround: 

```javascript
(function(HC) {
  HC.wrap(HC.Tick.prototype, 'replaceMovedLabel', function(proceed) {
if (!this.isGrouped) {
  if (!this.axis.isGrouped) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
  }
}
});
})(Highcharts)
```

**Live demo:**
https://jsfiddle.net/BlackLabel/Lyvfm8os/

**Comment by wjhcc2018** [comment]
@ mateuszkornecki，bug，when update xAxis，the code not executed；
**live demo:**https://jshare.com.cn/temp/SeGrWa
![image](https://user-images.githubusercontent.com/6789138/87656549-35316580-c78c-11ea-841c-8a2751843ffe.png)
![image](https://user-images.githubusercontent.com/6789138/87656618-4d08e980-c78c-11ea-9830-0aaee8b3281f.png)
```js
(function(HC) {
	HC.wrap(HC.Tick.prototype, 'replaceMovedLabel', function(proceed) {
		alert("hello，I'm here")
		if (!this.isGrouped) {
			if (!this.axis.isGrouped) {
				proceed.apply(this, Array.prototype.slice.call(arguments, 1));
				proceed.apply(this, Array.prototype.slice.call(arguments, 1));
			}
		}
	});
})(Highcharts)
var chart =  Highcharts.chart({
	chart: {
		renderTo: "container",
		type: "bar"
	},
	title: {
		useHTML: true,
		x: -10,
		y: 8,
		text: '<span class="chart-title"> Grouped categories <span class="chart-href"> <a href="http://www.blacklabel.pl/highcharts" target="_blank"> Black Label </a> </span> <span class="chart-subtitle">plugin by </span></span>'
	},
	series: [{
		data: [4, 14, 18, 5, 6, 5, 14, 15, 18]
	}],
	xAxis: {
		labels: {
			enabled: true,
			style: {
				fontSize: 19+'px',
				fontFamily:'Microsoft YaHei',
				colorAdaption: true,
				color:'red',
				maxWidth:50+'px',
				overflow:'hidden'
			},
			useHTML:true,
			//文字旋转方向
			rotation:0,
		},
		categories: [{
			name: "如懿班",
			categories:[
				{
					name:'一年级',
					categories:["卫嬿婉", "青樱"]
				},
				{
					categories: ["惢心", "江与彬"],
					name: "二年级"
				}
			]
		}, {
			name: "少年班",
			categories:[
				{
					name:'一年级',
					categories:["吕不韦", "李大国", "王俊凯", "王晓丽", "王有才", "秦晓莲"]
				},
				{
					categories: ["刘乔", "刘爱国", "崔振宇"],
					name: "二年级"
				}
			]
		}]
	}
});
setTimeout(function() {
	Highcharts.charts[0].update({
		xAxis: {
			labels:{
				style:{
					fontSize: 12+'px',
					fontFamily:'Microsoft YaHei',
					colorAdaption: true,
					color:'green',
					maxWidth:50+'px',
					overflow:'hidden'
				},
			}
		},
	});
}, 1000);

```

**Comment by mateuszkornecki** [comment]
The package has been published, so you don't need to use my plugin anymore. According to another problem you have reported recently - it looks like another bug that is not related to #157 or #146 

 I already reported it here: https://github.com/blacklabel/grouped_categories/issues/163. Since it is happening only with the `labels.useHTML` = `true` you can just disable HTML labels to bypass the problem.
