### ISSUE TITLE
autoRotation property not working for groupedCatgeories with HC v8.1.2 and higher

### ISSUE THREAD

**Issue by praveenvitara** [blacklabel/grouped_categories#165]
when using Highcharts 8.1.2 with latest grouped-categories.js module, the autoRotation functionality is not working.

Please find the sample chart reproducing the issue.

http://jsfiddle.net/praveenx9/yerkfs2p/

in the fiddle resize the chart container to see the autoRotation not working, while commenting the latest version and uncommenting the HC 6.2 version you can observe the autoRotation working while resizing the chart container.

**Comment by pawelfus** [comment]
Thanks for reporting the issue. It's a duplicate of #137.
