### ISSUE TITLE
Problems with x-axis when using library

### ISSUE THREAD

**Issue by dkoltg** [blacklabel/grouped_categories#174]
Hi, since yesterday, there seems to be a problem with displaying highcharts graphs when using your library for grouped categories and definitions of x-axis categories within the xaxis-variable. Here an example: https://jsfiddle.net/statistik_tg/juf14kzg/1/
Is there a way to use both options on the same time?

**Comment by hbingal** [comment]
I'm encountering the same issue with the latest highcharts 9.1.0 version published on 5/4/2021.
The issue is most likely related to the axis label context update.
Please help to check into this.

**Comment by KacperMadej** [comment]
Thank you for reporting the bug.
The current version of the plugin is not working with Highcharts v9.1.0.

**Comment by dkoltg** [comment]
Thank you for your reply, is there an updated version planed?

**Comment by KacperMadej** [comment]
Yes, the update fixing this problem is planned for Monday.
As a workaround, you could use Highcharts v9.0.1 (previous to the current 9.1.0)

**Comment by dkoltg** [comment]
Thank you. I've justed checked the example in jsfiddle above, that still does not work properly. Is there anything else I need to change? And if yes, what would that be? Thank you.

**Comment by KacperMadej** [comment]
The release is now available on NPM and GH - in case of an older version loading instead of v1.2.0 try clearing cache and forcing download from the server. If this doesn't help please share the problematic URL and/or create a live demo for the problem.
