### ISSUE TITLE
Compatibility issue with Highcharts JS v9.1.0 ?

### ISSUE THREAD

**Issue by lsokal** [blacklabel/grouped_categories#175]
Hi,

First of all, thank you for your work.
I found your project and it's filling a gap in a tool I am currently developing.

I noticed my latest grouped charts were not working anymore when using the latest CDN, as of now:
Highcharts JS v9.1.0 (2021-05-03)

After linking to a previous version of highcharts (8), it's working again.

The error I am getting with Highcharts JS v9.1.0 (2021-05-03) is 
_Uncaught TypeError: tick.axis.labelFormatter is undefined_ on line 383

`tick.label.attr('text', tick.axis.labelFormatter.call({`

I wanted to let you know, maybe I will have a look at it myself later on.

Cheers

**Comment by dugokontov** [comment]
@lsokal as far as I can see, this is the same issue that is fixed with #176 

I worked with 9.0.1

**Comment by KacperMadej** [comment]
Thank you for reporting the problem.
It is now resolved since the version 1.2.0 of the plugin.
