### ISSUE TITLE
Image instead of category name

### ISSUE THREAD

**Issue by dkoltg** [blacklabel/grouped_categories#208]
Hi, would it be possible to replace the text for each category name in a grouped-label-plot by an image (see sample code, line 40: https://jsfiddle.net/statistik_tg/vs1ct7pg/1/)? Thanks.

**Comment by hubertkozik** [comment]
Hello!
To use images as axis labels you have to set `xAxis.labels.useHTML` property to `true`. It will allow the rendering of HTML elements on the x-axis, which will enable the image tag in the axis labels.

Live demo: https://jsfiddle.net/BlackLabel/Ljwenr79/
