### ISSUE TITLE
Problem in applying formatter

### ISSUE THREAD

**Issue by samira2** [blacklabel/grouped_categories#46]
I faced a problem recently , I want to apply some format in category labels of each category,
It's working for all levels of grouped category but this format is not applying to final level of grouped-category.
Could you help me to solve this problem?

My formatter :

labels:{
  formatter: function(){
    if (this.value.length > 10){
        return this.value.substr(0,10) + "...";
    }else{
        return this.value;   
    }                        
  }
}

**Comment by pawelfus** [comment]
Live demo issue: http://jsfiddle.net/TFhd7/186/

**Comment by pawelfus** [comment]
Fixed: http://jsfiddle.net/TFhd7/195/

It's not ideal solution - formatter is called twice, but in that way we have backward compatibility.

**Comment by samira2** [comment]
Thank you So Much :) Is this bug fixed in your last release ?

**Comment by pawelfus** [comment]
Sure, just download above plugin again, or directly from [here](http://blacklabel.github.io/grouped_categories/grouped-categories.js).

**Comment by samira2** [comment]
Thanks ;)
