### ISSUE TITLE
how to hide the the second category

### ISSUE THREAD

**Issue by andrew-zenefits** [blacklabel/grouped_categories#50]
Is it possible to hide the second category?

In this [jsFiddle](http://jsfiddle.net/andrewscheuermann/dsx60475/) I'd like to hide the "Apple", "Banana", "Orange" category. 

Thanks

**Comment by pawelfus** [comment]
You can hide categories texts using spaces:

        xAxis: {
            categories: [{
                name: "Fruit",
                categories: [" ", " ", " "]
            }, {
                name: "Vegetable",
                categories: ["Carrot", "Potato", "Tomato"]
            }, {
                name: "Fish",
                categories: ["Cod", "Salmon", "Tuna"]
            },{
                name: "Grain",
                categories: ["Barley", "Oat", "Wheat"]
            }]
        }

Demo: http://jsfiddle.net/dsx60475/1/

**Comment by andrew-zenefits** [comment]
Sorry, let me clarify.

I'd like to remove the entire line. I'd like for the first three data sets to fall under fruit, the second three to fall under Vegetable, etc.

**Comment by pawelfus** [comment]
Then why do you use grouped categories plugin for such chart? In fact you should be using simple chart with three separated series: http://jsfiddle.net/dsx60475/2/

**Comment by andrew-zenefits** [comment]
This is what I was trying to accomplish. It's a unique request but I hadn't seen anyone else's solution so I made and answered a [SO question](http://stackoverflow.com/questions/27810279/highcharts-column-chart-with-separate-categories?noredirect=1#comment44053711_27810279).

**Comment by pawelfus** [comment]
Great, don't forget to accept your answer ;)
