### ISSUE TITLE
Reversed category for tooltip (still)

### ISSUE THREAD

**Issue by yohannbalawender** [blacklabel/grouped_categories#52]
Hi again,

Sorry for re-opening a new issue about that.

If I've got more than 2 levels of 'grouped categories', so the first ones are not displayed in tooltip.

Related to your example: 
  - what we have: " Very Famous Orchard, Granny Smith, Apple, Fruit ",
  - with your solution: " Apple, Granny Smith ",
  - what I would like to have: " Fruit, Apple, Granny Smith, Very Famous Orchard ".

Thanks for all.

**Comment by pawelfus** [comment]
See my answer in #51..

**Comment by yohannbalawender** [comment]
Got it, thanks.

formatter() was my first idea, but I find it complicated then a simple reverse() could fit in Category prototype.

Again, thanks for all.

**Comment by pawelfus** [comment]
When you look into the sources, you will find `Category.toString` method which is responsible for order. I'm not sure if this is necessary to add feature for something which can be achieved in one-liner:
 
    formatter: function() {
         var catString = this.key.toString().split(', ').reverse().join(', ');
         // reversed string in catString variable
         return "something";
    }

Demo: http://jsfiddle.net/TFhd7/197/

**Comment by yohannbalawender** [comment]
formatter seems to override all header, point and footer format, and I only needed to change the header format, so it forces me to rewrite all the point content.

**Comment by pawelfus** [comment]
Even, when adding such method to Category class, you will still need to use formatter to call it..

**Comment by yohannbalawender** [comment]
Indeed. Thanks for all !
