### ISSUE TITLE
Enable the xAxis' labels enabled option

### ISSUE THREAD

**Issue by yohannbalawender** [blacklabel/grouped_categories#53]
Hi, me again.

In my company, we have specific needs and we would like to display several large charts in one page. To do so, grouped-categories is automatically required with require.js.

We want to get rid if there are too many when we update a chart for optimization a nice rendering.

So, we used xAxis.labels: { enabled: false } and we've got an error vomitted in console:
> Uncaught TypeError: Cannot read property 'attr' of null grouped-categories.js:360

Is there any way more simple than "to crop" the categories tree ?

Thanks a lot sir.

**Comment by pawelfus** [comment]
Fixed, demo: http://jsfiddle.net/TFhd7/202/

**Comment by yohannbalawender** [comment]
Works in my case too.

Thanks for all !
