### ISSUE TITLE
Exception when grouped chart refreshed after no data

### ISSUE THREAD

**Issue by qsandi** [blacklabel/grouped_categories#54]
We found an execption when we use a grouped chart:
- group the chart
- filter the chart so that no data will be displayed anymore
- remove the filter and refresh the chart

=> exception: in line 306 "delete ticks[n].parent;" is not possible
Reason can be found in line 305:
current: *if (ticks[n].parent);*
can be fixed with: *if (ticks[n].parent)*
(remove the semicolon at the end of line 305)

**Comment by pawelfus** [comment]
Thank you for noticing this!

**Comment by ShanHuang** [comment]
can this be merged and put in release in anyway sooner? thanks.

**Comment by pawelfus** [comment]
Released new version.
