### ISSUE TITLE
New option 'hidden' for each group level

### ISSUE THREAD

**Issue by yohannbalawender** [blacklabel/grouped_categories#56]
Hey,

I'm coming with another issue :) I've got a special case where I've got a lot of point to display (about 200) with 4 or more categories' levels and on a screen 1280x1024, all categories are overlapping themselves. I can easily hide them remplacing their name by a whitespace but I still need to display the correct category in the tooltip.

I'm wondering if there is any way to add an 'hidden' option for each grouped category ?

Thanks !

**Comment by pawelfus** [comment]
How do you achieve the same in Highcharts without plugin? I see two solution right now for this case:

- use `formatter` to return whitespace when necessary
- set whitespace for categories, but for each point add info about category ( `data: [{ x: 10, y: 10, name: 'test', category: 'myCat' }]`, and later in `tooltip.formatter` get that category name.

**Comment by yohannbalawender** [comment]
This is a special case : I have many points to display, and without a large screen all categories are overflowing themselves. This problem only appear on third or fourth level, so I didn't try without plugin.

Plus, as a tooltip feature isn't concerned by the issue, that's why I would like to keep it.

**Comment by yohannbalawender** [comment]
Done, it works. I create 'fullLabelCategory' for each data for each serie, and I retrieve it from this.points[0].point.fullLabelCategory with formatter function.

Thanks for all !
