### ISSUE TITLE
data from MySQL and PHP

### ISSUE THREAD

**Issue by gledsoneduardo** [blacklabel/grouped_categories#57]
Hi!

First, sorry my terrible english,
Second, great job!

And question:

I have a MySQL table:
id, name, parent_id
1, america, null
2, usa, 1
3, new york, 2
4, los angeles, 2
5, canada, 1
6, otawa, 5
7, quebec, 5
8, europe, null
9, poland, 8
10, krakow, 9
11, warsa, 9
12, england, 8
13, london, 12

how to use this table and PHP and JQuery?

thanks!

**Comment by pawelfus** [comment]
Get data from PHP, send it do JS (AJAX?) and create chart? Read some tutorials how to get data from PHP and pass it to the JS. You just need to create proper format for grouped categories. Good starting point [here](http://www.highcharts.com/docs/working-with-data/data-from-a-database).

**Comment by gledsoneduardo** [comment]
Thanks Pawelfus, my chart works fine only one categorie, i can't use grouped categories, but i will study too much, thanks a lot.
