### ISSUE TITLE
Lost control on ticks

### ISSUE THREAD

**Issue by kjm** [blacklabel/grouped_categories#58]
Global options like yAxis.tickAmount and yAxis.tickLength not works.
It looks that plugin don't use global options for them.

**Comment by pawelfus** [comment]
How do you expect `Axis.tickAmount` to work on grouped categories? 
`Axis.tickLength` never suppose to work, since you have grid/table for categories.

**Comment by kjm** [comment]
Maybe i should be more precise,
yes, i expect that NOT GROUPED axis will work as it should. :)

**Comment by pawelfus** [comment]
Do you have some live jsfiddle demo? We will be able to check this then.

**Comment by kjm** [comment]
I've dig problem deeper and here's some clarification.
TickAmount is bugged in highcharts 4.0.4 which I've used. On latest 4.1.2 it works, but other things stops working properly :( 
Problem with ticks on grouped axis for me still exist. Maybe it is by design, i don't know.
What i expect? I wanna disable ticks on groupped axis to hide them by setting length to 0 or set color to white.
Here it's done without groupped categories - http://jsfiddle.net/tvex93Lu/
With groupped categories its imposible because i haven't control over tick color or length. Table is made using color inherited from axis lineColor instead of tickColor. I can't disable axis lineColor because i need it.
Here's example - http://jsfiddle.net/pqvej3h6/1/

For now i've found workaround and got what i want.
Maybe in the future u will change that ? :)

Btw, it's really great plugin and help me a lot.

Regards
Konrad

**Comment by pawelfus** [comment]
So separating tick-options and line-options should resolve issue? 

`tickAmount` is new feature in Highcahrts 4.1.x, so I don't think that would work in 4.0.x ;)

**Comment by kjm** [comment]
It would be great.
Thx for your help :)

Regards
