### ISSUE TITLE
Cannot set y position for Labels. 

### ISSUE THREAD

**Issue by aliulichev** [blacklabel/grouped_categories#59]
Hi, 

When we try this code below:

               groupedOptions: [{
                    y:17,
                    style: {

                        color: 'red' // set red font for labels in 1st-Level
                    }
                }]
Setting y property does not give any effect.

**Comment by pawelfus** [comment]
**Workaround**: <br> you can set `translateY: 17,` instead of `y: 17,`.

*Internal note:* <br>
When merging options with default one, we need to replace "y" with "translateY". The same with x-param.
