### ISSUE TITLE
Cannot disable lineWidth

### ISSUE THREAD

**Issue by mbhenning** [blacklabel/grouped_categories#60]
It is currently not possible to disable the border on the grouped categories when setting lineWidth to 0.

```javascript
this.options.lineWidth = options.lineWidth || 1;
```

It will work if you change the code on line 192 to 
```javascript
this.options.lineWidth = options.lineWidth >= 0 ? options.lineWidth : 1;
```

**Comment by pawelfus** [comment]
Sorry for a delay!
`lineWidth` isn't used anymore. To disable that line use `tickWidth`, demo: http://jsfiddle.net/TFhd7/323/
