### ISSUE TITLE
Hiding child categories

### ISSUE THREAD

**Issue by R4GN4R0K** [blacklabel/grouped_categories#61]
I want to know if it's possible to hide the first child category so i can have a bigger chart, something like step in x axis label, but for all the labels in the child category.

Thanks in advance, and zorry for my bad english.

**Comment by pawelfus** [comment]
Could you show the demo? How hiding first category name will make your chart bigger? jsFiddle demo with more information would be great.

**Comment by R4GN4R0K** [comment]
Thanks for the reply, i can't make a demo right now but i want to do something like this below. The thing is that in the second img. i'm not sending values for the child category so i can't watch'em in the tooltip.
I would like to just hide it in the X axis but i still want to watch'em in the tooltip.
with the child category shown:
http://oi60.tinypic.com/mme99u.jpg
without the child category shown:
http://oi59.tinypic.com/2eex8yb.jpg

**Comment by pawelfus** [comment]
I think you can simply use formatter to hide names, or set empty category names. If you would create jsfiddle demo (with randomized data), I could you help more.

**Comment by R4GN4R0K** [comment]
I'm taking this example, i hope you could help me :).
http://jsfiddle.net/4x1b7b2v/1/

**Comment by pawelfus** [comment]
And here you are: http://jsfiddle.net/4x1b7b2v/2/ ;)

**Comment by R4GN4R0K** [comment]
Thank you very much :), you saved me a lot of effort
