### ISSUE TITLE
SVG export doesn't show correct height of grouped categories

### ISSUE THREAD

**Issue by thejensi1** [blacklabel/grouped_categories#64]
I think I've found an issue with the grouped categories plugin.
In my company we use HighCharts to visualize huge data, and we need to have grouped categories as well. When plotting the charts on the website, everything shows up fine:

![grouped_issue_1](https://cloud.githubusercontent.com/assets/9960190/8500170/b8d845b4-2199-11e5-873c-e6b8b834d08b.jpg)

But when exporting it to SVG and converting the SVG via HTML-canvas to an image, the grouped categories lost their height:

![grouped_issue_2](https://cloud.githubusercontent.com/assets/9960190/8500183/d1991b5a-2199-11e5-9632-3a4333758b04.jpg)

(Needed to paint over the category names because of company disclosure.)

Has anybody of you a solution for that?
If you need further information, please let me know.

**Comment by pawelfus** [comment]
Could you create simple jsFiddle demo with that issue? With some randomized data and categories, just for a demo purpose.

**Comment by thejensi1** [comment]
Just solved the issue by myself with adding an event handler to the chart's load-event which hides the first series and immediately shows it again which makes the chart grouped categories to realign. So everything is fine again :)
