### ISSUE TITLE
Category borders are misaligned against the grid lines.

### ISSUE THREAD

**Issue by art-solopov** [blacklabel/grouped_categories#65]
Here's a bar graph with grouped categories I've created:

![hcgc1](https://cloud.githubusercontent.com/assets/5079987/8521482/9db3e3b0-23ec-11e5-94f6-1a07eaa54c18.png)

My problem is, basically, these areas:

![hcgc2](https://cloud.githubusercontent.com/assets/5079987/8521489/a948fd5a-23ec-11e5-9803-03309e832222.png)

The grid lines on the categories aren't aligned against the grid lines of the chart itself. The "gap" between the two lines may vary, and I can't find out what it depends on.

I know it's a small change, but it's a noticeable one and it's not aesthetically pleasing.

Here's [the code](https://www.dropbox.com/s/sigzx9v1zyom54y/hcgc.tar.gz?dl=0) (wasn't able to make a JsFiddle work properly).

**Comment by pawelfus** [comment]
Internal note:
It looks like Highcharts are using different logic for rendering horizontal lines/marks (crisped lines).
