### ISSUE TITLE
Label alignment not proper

### ISSUE THREAD

**Issue by reXADHIX** [blacklabel/grouped_categories#67]
![grouped3](https://cloud.githubusercontent.com/assets/11803220/9734895/5ec4ad84-5654-11e5-8bca-a7727f3e400f.PNG)
Assigning values to "xAxis.label.align" does not align the xAxis labels properly.

"right" aligns it slightly to the left (but not entirely).
"left" aligns it slightly to the right (but not entirely).

[Please check jsFiddle here : http://jsfiddle.net/xadhix/x8f79cp5/](http://jsfiddle.net/xadhix/x8f79cp5/)

![grouped1](https://cloud.githubusercontent.com/assets/11803220/9734742/3890469c-5653-11e5-9baa-1773cdbe7a72.PNG)
![grouped2](https://cloud.githubusercontent.com/assets/11803220/9734743/3899d40a-5653-11e5-85aa-6f028eb77d6a.PNG)

**Comment by pawelfus** [comment]
This is how `labels.align` works, see [API](http://api.highcharts.com/highcharts#xAxis.labels.align). It doesn't align label within the box, but aligns how text should behave (demo without grouped categories: http://jsfiddle.net/x8f79cp5/3/ ). Middle of the category is point where categories are anchored. You can see, that `align: "right"` makes label **end** in the middle, and `"left"` **starts** in the middle.

PS: For general support, I suggest to use forum/stackoverflow.

**Comment by reXADHIX** [comment]
Thanks for the clarification. My bad. Sorry for the confusion.
