### ISSUE TITLE
Can we use rcharts to plot Grouped_Categories charts?

### ISSUE THREAD

**Issue by King23** [blacklabel/grouped_categories#69]
Hi,

I am really appreciate the grouped_categories charts (Highcharts) that being created, really cool stuff and like it a lot. I am very interested to use R to plot the grouped_categories charts..
Can you let me know is rCharts package able to do so? If yes, can you show me some simple example R code for the grouped_categories chart just for reference so i can start to build from there?

appreciate and thanks

**Comment by KacperMadej** [comment]
From github files for rChart I can see that only highcharts, highcharts-more and exporting module is being loaded, so grouped categories module is not supported by default. It looks more like a question to rCharts authors - how to include and use additional Highcharts related files, such as modules.

**Comment by King23** [comment]
Thank you very much for the advice. Looks like i have to go back and ask rChart author.

**Comment by King23** [comment]
Hi KacperMadej,
Any idea where i can find the online source for the Grouped_Categories.js file? I am trying to follow the installation note to add <script> tag pointing to grouped-categories.js file. I check in the code.highcharts.com below, i can't see it just the like the exporting.js module. Hope you can guide me. THANKS!

http://code.highcharts.com/

**Comment by KacperMadej** [comment]
1. At github master branch: 
http://rawgit.com/blacklabel/grouped_categories/master/grouped-categories.js

2. From demo:
http://blacklabel.github.io/grouped_categories/grouped-categories.js

(3? Use download button from plugin site on Highcharts plugins list - but this will provide zipped folder with more than just the grouped_categories.js: http://www.highcharts.com/plugin-registry/single/11/Grouped-Categories)

**Comment by King23** [comment]
Thank You KacperMadej, you are superb!!! :)

**Comment by King23** [comment]
Thanks so much for the info! ^_^

On Thursday, October 1, 2015, Kacper Madej <notifications@github.com> wrote:
> At github master branch:
>
http://rawgit.com/blacklabel/grouped_categories/master/grouped-categories.js
>
> From demo:
> http://blacklabel.github.io/grouped_categories/grouped-categories.js
>
> (3? Use download button from plugin site on Highcharts plugins list - but
this will provide zipped folder with more than just the
grouped_categories.js:
http://www.highcharts.com/plugin-registry/single/11/Grouped-Categories)
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/akxRkaZiJXni7BXqLDV3DU6hc0FUxC2_sfP7hPKoENw9IX6rNBBMJ27-dxHQkNeEMRo7kqj2PpfaDbt7RJ3gpNWoP6SSRoYkW394Ca2tHDQMv4LFJ8X844ahTaH4pMBMwMudbfVN69COxHziEA-dtiBLWKlSOA=s0-d-e1-ft#https://github.com/notifications/beacon/AMsumK-BZRBm9Ry_E6LCN6GtWjVg2894ks5o3O1RgaJpZM4GGWs-.gif
>
