### ISSUE TITLE
Box not getting closed properly when used in y grouping

### ISSUE THREAD

**Issue by onkaragarwal** [blacklabel/grouped_categories#70]
Hi

I have tried to implement grouping in y axis as shown below
http://jsfiddle.net/tmv24hjd/

If you see the box is not getting closed at the top.Can you please let me know what is the issue and solution for it

**Comment by KacperMadej** [comment]
Workaround: increase slightly max for yAxis - http://jsfiddle.net/tmv24hjd/1/

**Comment by onkaragarwal** [comment]
Thanks for the workaround

**Comment by pawelfus** [comment]
You can render inner tooltip in html too, see [tooltip.useHTML](http://api.highcharts.com/highcharts#tooltip.useHTML). 

However, this will still render background/border/shadows in SVG. I suggest to disable this options and create them in HTML tooltip formatter. Unfortunately pointer will be lost.

**Comment by pawelfus** [comment]
Minified demo: http://jsfiddle.net/tmv24hjd/2/
