### ISSUE TITLE
xAxis labels are get overlapped when 0-level categories are rotated

### ISSUE THREAD

**Issue by yplakosh** [blacklabel/grouped_categories#72]
The labels of 0-level categories are get overlapped when rotation is applied to them.

It is reproducible for specific viewport size.

height: 900px; width: 1000px - issues: 
http://jsfiddle.net/pgz4kfee/ 

height: 800px; width: 1000px - no issues:
http://jsfiddle.net/tzw1dLac/

height: 900px; width: 600px - no issues:
http://jsfiddle.net/xneejd3n/

This issue is reproducible also only starting from Highcharts 4.1.0. I cannot reproduce it on 4.0.4.

**Comment by KacperMadej** [comment]
I am unable to reproduce your issue - labels are looking the same (only in 3rd they are closer, but still doesn't overlap) in all examples. What OS and web browser are you using? Could you post a screen shot of the problem?

**Comment by yplakosh** [comment]
Google Chrome Version 46.0.2490.80 (64-bit)
Mac OS 10.10.5

**Comment by yplakosh** [comment]
<img width="1246" alt="screen shot 2015-10-29 at 8 56 47 am" src="https://cloud.githubusercontent.com/assets/4722300/10851826/7c4a7bf4-7eea-11e5-918f-db41413ebd90.png">

**Comment by KacperMadej** [comment]
This fix should resolve the problem. Problem was replicated, resolved and tested, but it would be appreciated if you could check if now labels are rendered properly.

**Comment by yplakosh** [comment]
Your fix works. Thank you.
