### ISSUE TITLE
X labels get overlapped

### ISSUE THREAD

**Issue by dmitrygorbenko** [blacklabel/grouped_categories#73]
hi !

pls, take a look at this fiddle:
http://jsfiddle.net/jaLacrh0/

the labels on X axis get overlapped.

![overlapped](https://cloud.githubusercontent.com/assets/1971759/10882806/798ffda6-8176-11e5-8d84-fc39283a8a15.jpeg)

Can it be improved in some way ?

**Comment by KacperMadej** [comment]
We could add step for other levels in groupedOptions, but will this solve the problem? Other option might be to show labels from higher level only if at least one of its subcategory label is visible, so also based on step option. Do you have any suggestions?

**Comment by dmitrygorbenko** [comment]
I was thinking about this, and I think we should close this ticket as is.
I mean, there is definetly no good way to solve it, each one would have some disadvantages.
Sorry about raising this question.
