### ISSUE TITLE
Categories are not showing up correctly. X axis's labels are showing up as [Object object]

### ISSUE THREAD

**Issue by lavkesh** [blacklabel/grouped_categories#75]

**Comment by KacperMadej** [comment]
Do you have a live demo showing the problem? Are you using latest version of the Grouped Categories plugin? Only after [last fix](https://github.com/blacklabel/grouped_categories/commit/23595abfa015f6141d4938967db1f28823f59697) Highcharts in version 4.1.10 is working.

**Comment by lavkesh** [comment]
http://www.highcharts.com/plugin-registry/single/11/Grouped-Categories
See the graphs in above link.
