### ISSUE TITLE
does not work for columnrange if yes whatshould be the sample data for columnrange 

### ISSUE THREAD

**Issue by nitanshu** [blacklabel/grouped_categories#80]
can invert it but not able to use the data for columnrange please help if columnrange available

**Comment by pawelfus** [comment]
It works with columnrange, example: 

    var chart = new Highcharts.Chart({
        chart: {
            renderTo: "container",
            type: "columnrange",
            borderWidth: 5,
            borderColor: '#e8eaeb',
            borderRadius: 0,
            backgroundColor: '#f7f7f7'
        },
        title: {
            style: {
                'fontSize': '1em'
            },
            useHTML: true,
            x: -27,
            y: 8,
            text: '<span class="chart-title"> Grouped categories <span class="chart-href"> <a href="http://www.blacklabel.pl/highcharts" target="_blank"> Black Label </a> </span> <span class="chart-subtitle">plugin by </span></span>'
        },
        series: [{
            data: [ [4, 11], [5, 14], [5, 18], [5, 10], [6, 11], [1, 5], [11, 14], [9, 15], [5, 18]]
        }],
        xAxis: {
            categories: [{
                name: "Fruit",
                categories: ["Apple", "Banana", "Orange"]
            }, {
                name: "Vegetable",
                categories: ["Carrot", "Potato", "Tomato"]
            }, {
                name: "Fish",
                categories: ["Cod", "Salmon", "Tuna"]
            }]
        }
    });

Make sure you didn't forget `highcharts-more.js` file in your app.

**Comment by nitanshu** [comment]
thanks Paweł yes it does and and it works for me and sharing a link which will be helpful for others in terms of options [(http://jsfiddle.net/TFhd7/368/)]
