### ISSUE TITLE
Pie position

### ISSUE THREAD

**Issue by sebastianbochan** [blacklabel/grouped_categories#86]
The grouped-categories casues an issue with pie position, when init hidden series.

Steps to reproduce.
1) http://jsfiddle.net/xznbohek/
2) Hide all series by legend
3) Click green legend item (pie chart is displayed in wrong place)
4) Click any other item, pie chart moves.

Problem appears only when grouped-categories is used.

**Comment by KacperMadej** [comment]
Without grouped-categories the issue is still visible - http://jsfiddle.net/44rzkcjL/
