### ISSUE TITLE
Group categories for time series

### ISSUE THREAD

**Issue by zhy1stgg** [blacklabel/grouped_categories#89]
Hi, How to grouped categories in time series ?

**Comment by KacperMadej** [comment]
There is no categories in datetime type axis, so it is not possible to group categories.

Another option for you could be to add linkedTo axis with different tick placement.
Example: http://jsfiddle.net/x3uavww1/

In case of questions not related to the plugin please use [highcharts support](http://www.highcharts.com/support).

**Comment by zhy1stgg** [comment]
ok, Thanks very much.
